CREATE INDEX POSTES_COORD_X_IDX ON POSTES(COORD_X)
/
CREATE INDEX POSTES_COORD_Y_IDX ON POSTES(COORD_Y)
/
CREATE INDEX POSTES_EXTRAS_OBJECT_ID_IDX ON POSTE_EXTRAS(poste_objectid)
/
CREATE INDEX POSTES_EXTRAS_POSTE_ID_IDX ON POSTE_EXTRAS(poste_id)
/

