load data
 infile 'postes.csv'
 into table postes
 fields terminated by "," optionally enclosed by '"'		  
 ( OBJECTID, USUARIOREG, FECHAREGIS "to_date(:FECHAREGIS, 'MM/DD/YY')", FECHAMODIF "to_date(:FECHAMODIF, 'MM/DD/YY')", USUARIOMOD, PROYECTOCO, FECHACONST "to_date(:FECHACONST, 'MM/DD/YY')", FECHAACTIV "to_date(:FECHAACTIV, 'MM/DD/YY')", PROYECTOMO, FECHAMOD_1 "to_date(:FECHAMOD_1, 'MM/DD/YY')", CODIGOEMPR, PROVINCIA, CANTON, PARROQUIA, CASERIO, CODIGOELEM, SUBTIPO, PROPIEDAD, HIPERVINCU, TIPOCIMIEN, ATERRAMIEN, CODIGOESTR, ROTACIONSI "to_number(:ROTACIONSI, '999999990.99999999999990','NLS_NUMERIC_CHARACTERS = ''.,''')" , MISUBTIPO, ESTRUCTURA, ESTADO, MIOID, GLOBALID, PUESTOATIE, COMENTARIO, TEXTOETIQU, MIGUID, MIESTADO, EXISTENOVE, OBSERVACIO, COORD_X "to_number(:COORD_X, '999999990.99999999999990','NLS_NUMERIC_CHARACTERS = ''.,''')" , COORD_Y "to_number(:COORD_Y, '999999990.99999999999990','NLS_NUMERIC_CHARACTERS = ''.,''')" , ALIMENTADO, TIPOUSOPOS )
